### ISSUE TITLE
Make settings animation faster/smooth

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-android#48]
How it looks now (on the actual smartphone it feels more slow):
https://user-images.githubusercontent.com/5204968/216410257-99004811-fa82-4928-9286-e988bd263e61.mp4

**Comment by Reddnek** [comment]
You mean the choppiness or the duration?

For the duration I can have that tweaked

As for the choppiness, it's due to the use of gradient colors for those widgets as well as the animation itself, I am adding a 'performance UI mode' setting in the next release to make sure such animations look smoother, by not rendering the gradients at all and using a solid color instead

**Comment by soredake** [comment]
> You mean the choppiness or the duration?

Both i guess.

>As for the choppiness, it's due to the use of gradient colors for those widgets as well as the animation itself, I am adding a 'performance UI mode' setting in the next release to make sure such animations look smoother, by not rendering the gradients at all and using a solid color instead

Thanks!

**Comment by yuroyami** [comment]
Fixed in [version (0.12.0)](https://github.com/yuroyami/syncplay-android/releases/tag/v0.12.0)

**Comment by soredake** [comment]
@yuroyami thank you!
