### ISSUE TITLE
Question: vp9 video having bad framerate in syncplay-android but plays fine in vlc, can something be done with this?

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-android#55]
It seems like hardware decoding for vp9 is not working on my tablet in syncplay-android.

**Comment by yuroyami** [comment]
Seems like a software-decoding issue indeed, I tested with a VP9 on some of my devices, the high-end ones seem to work fine but the mid to low-end ones struggle with playback.

I might resort to implementing some option to switch between software & hardware decoding although I am not sure how it's gonna turn out. In 99% of cases for Android, it's always better to have software decoding since the hardware one consumes 30% more computing power (thus, draining battery 30% faster) and in said cases the outcome can be even worse. But, we'll see if it works for extreme cases like this

As for VLC, it wraps FFmpeg so it has its own built-in decoders which is why it happens to play everything with ease, but it's pretty unstable. We'll go with the first workaround by the next version

**Comment by soredake** [comment]
I realized that my tablet can play only up to 1080p, and video with bad framerate was 1200p, closing.
